import { publicAssetPath } from "@/lib/site";

export const workHero = {
  eyebrow: "Case Proof Library",
  title: "用實績看道易如何把複雜資料做成可查、可驗、可維護的平台",
  description:
    "道易案例橫跨 DPP、ESG、AI-Ontology、研究資料庫與資料平台。重點不是展示畫面，而是把分散資料整理成可用系統。",
};

export const caseCategories = [
  {
    id: "dpp-esg",
    title: "DPP / ESG / 循環經濟",
    detail: "產品資料、回收履歷、ESG 稽核與供應鏈揭露。",
    examples: ["Easy DPP 數位產品護照", "太陽能板回收 YOLO 辨識與履歷"],
    href: "#featured-cases",
    cta: "查看 DPP / ESG 案例",
  },
  {
    id: "ai-ontology",
    title: "AI-Ontology / 數位人文",
    detail: "人物、作品、事件、文本與研究資料。",
    examples: ["國立臺灣文學館好臺誌、外譯房", "社會網絡分析與人物知識本體"],
    href: "#featured-cases",
    cta: "查看 AI-Ontology 案例",
  },
  {
    id: "research",
    title: "國際研究 / 知識平台",
    detail: "多語系資料、linked data 與研究資料庫。",
    examples: ["Taiwan Biographical Ontology", "ORIENT Card Catalog", "TLiT"],
    href: "#featured-cases",
    cta: "查看研究平台案例",
  },
  {
    id: "data-platform",
    title: "資料平台 / 系統整合",
    detail: "既有資料庫、舊系統、後台、查詢頁或 API。",
    examples: ["香港中文大學圖書館傳記資料庫", "土地台帳建檔輔助系統"],
    href: "#featured-cases",
    cta: "查看資料平台案例",
  },
];

export const caseStudies = [
  {
    id: "easy-dpp",
    title: "Easy DPP 數位產品護照",
    category: "DPP / 產品履歷 / 供應鏈透明 / ESG",
    filterGroup: "DPP / ESG",
    image: {
      src: publicAssetPath("/assets/cases/dpp-qr-query-demo.svg"),
      alt: "DPP QR 查詢頁公開重繪示意圖",
      caption: "公開重繪示意圖：DPP QR 查詢頁 demo",
    },
    summary: "把產品資料整理成可掃描、可維護的數位身分。",
    problem: "材料、來源、製程與回收指引分散在部門、供應商與文件中。",
    solution: "道易整理 DPP 架構、公開查詢頁與後台維護邏輯。",
    deliverables: ["DPP 欄位藍圖", "QR Code 查詢頁原型", "後台資料維護流程"],
    extension: "適合製造、品牌、材料與循環經濟團隊先做 DPP PoC。",
    tags: ["DPP", "QR Code", "Traceability", "Supply Chain", "ESG"],
    ctaLabel: "討論 DPP PoC",
    ctaHref: "/contact?topic=dpp-poc",
    proofStatus: "公開素材：DPP QR 查詢頁重繪示意圖。",
  },
  {
    id: "solar-recycling",
    title: "太陽能板回收 YOLO 辨識與履歷",
    category: "AIoT / 回收履歷 / ESG 稽核 / Data Trust Chain",
    filterGroup: "DPP / ESG",
    image: {
      src: publicAssetPath("/assets/cases/recycling-traceability-dashboard.svg"),
      alt: "AIoT 回收履歷查核結果 Dashboard 公開重繪示意圖",
      caption: "公開重繪示意圖：AIoT 回收履歷 Dashboard",
    },
    summary: "把影像、設備、批次與回收流程整合成可追溯履歷。",
    problem: "回收資料分散在影像、設備、批次與人工紀錄中。",
    solution: "道易整合 YOLO、現場資料與回收履歷，規劃可查核資料結構。",
    deliverables: ["AI 影像辨識資料整合", "回收批次資料模型", "Dashboard 與信任鏈規劃"],
    extension: "適合回收、再生資源與 ESG 查核團隊。",
    tags: ["AIoT", "YOLO", "Traceability", "ESG Audit"],
    ctaLabel: "討論回收履歷整合",
    ctaHref: "/contact?topic=recycling-traceability",
    proofStatus: "公開素材：回收履歷 Dashboard 重繪示意圖。",
  },
  {
    id: "nmtl",
    title: "國立臺灣文學館好臺誌、外譯房",
    category: "數位人文 / 知識平台 / 語意資料 / 文化資料",
    filterGroup: "AI-Ontology",
    image: {
      src: publicAssetPath("/assets/cases/tlsg-nmtl-card.jpg"),
      alt: "文學好臺誌公開網站截圖",
      caption: "公開截圖：文學好臺誌 / NMTL",
    },
    summary: "把文學資料、人物、作品與歷史脈絡整理成可探索平台。",
    problem: "人物、作品、地點、主題與年代關係不易用一般網站呈現。",
    solution: "道易建置可查詢、可維護的數位人文資料平台。",
    deliverables: ["文學資料結構設計", "前台查詢展示", "後台內容維護流程"],
    extension: "適合文化館所、博物館、圖書館與研究計畫。",
    tags: ["Digital Humanities", "Knowledge Platform", "Metadata", "Semantic Search"],
    ctaLabel: "討論數位人文平台",
    ctaHref: "/contact?topic=digital-humanities",
    proofStatus: "公開素材：文學好臺誌公開網站截圖。",
  },
  {
    id: "tbio",
    title: "Taiwan Biographical Ontology",
    category: "國際研究 / 人物本體 / Linked Data / Knowledge Graph",
    filterGroup: "研究資料庫",
    image: {
      src: publicAssetPath("/assets/cases/tbio-card.png"),
      alt: "Taiwan Biographical Ontology 公開網站截圖",
      caption: "公開截圖：Taiwan Biographical Ontology / Oriental Institute, Czech Academy of Sciences",
    },
    summary: "把人物、組織、職位與生命歷程整理成研究資料庫。",
    problem: "傳記資料橫跨人物、組織、職位、地點與來源，缺少本體架構難以重用。",
    solution: "道易以人物本體支援瀏覽、語意查詢、下載與資料集貢獻。",
    deliverables: ["人物本體資料模型", "研究資料查詢介面", "資料來源與下載流程"],
    extension: "適合國際研究機構、大學研究中心與大型人物資料計畫。",
    tags: ["Ontology", "Prosopography", "Linked Data", "Knowledge Graph"],
    ctaLabel: "討論研究資料庫",
    ctaHref: "/contact?topic=research-database",
    proofStatus: "公開素材：TBIO 公開首頁截圖。",
  },
  {
    id: "cuhk-biography",
    title: "香港中文大學圖書館傳記資料庫",
    category: "圖書館 / 傳記資料 / 搜尋系統 / 知識平台",
    filterGroup: "圖書館 / 資料平台",
    image: {
      src: publicAssetPath("/assets/cases/biography-database-search.svg"),
      alt: "人物資料庫搜尋與詳情頁公開重繪示意圖",
      caption: "公開重繪示意圖：人物資料庫搜尋與詳情頁",
    },
    summary: "把傳記資料整理成可搜尋、可維護的平台。",
    problem: "人物資料需要兼顧權威性、搜尋效率、來源與詳情呈現。",
    solution: "道易規劃人物資料結構、分類、搜尋與後台維護流程。",
    deliverables: ["人物資料模型", "搜尋與篩選介面", "資料來源紀錄設計"],
    extension: "適合圖書館、典藏單位與研究資料中心。",
    tags: ["Biography Database", "Library", "Metadata", "Search"],
    ctaLabel: "討論人物資料平台",
    ctaHref: "/contact?topic=biography-platform",
    proofStatus: "公開素材：人物資料庫搜尋與詳情頁重繪示意圖。",
  },
  {
    id: "sna-ontology",
    title: "社會網絡分析與人物知識本體",
    category: "Ontology / 社會網絡分析 / Knowledge Graph / Visualization",
    filterGroup: "AI-Ontology",
    image: {
      src: publicAssetPath("/assets/cases/lxt-sna-card.jpg"),
      alt: "社會網絡分析平台公開網站截圖",
      caption: "公開截圖：社會網絡分析平台",
    },
    summary: "把人物、事件、組織與地點關係轉成知識網絡。",
    problem: "人物關係分散在文本與研究紀錄中，缺少模型時難以查詢。",
    solution: "道易建立語意模型，支援關係查詢與社會網絡分析。",
    deliverables: ["人物與事件本體模型", "關係資料整理", "知識圖譜視覺化"],
    extension: "適合研究團隊、文化機構與政府資料平台。",
    tags: ["Ontology", "SNA", "Knowledge Graph", "Visualization"],
    ctaLabel: "討論知識圖譜平台",
    ctaHref: "/contact?topic=knowledge-graph",
    proofStatus: "公開素材：社會網絡分析平台截圖。",
  },
];

export const workMethodSteps = [
  { step: "01", title: "盤點資料來源", detail: "確認資料來自系統、文件、影像、設備或人工紀錄。" },
  { step: "02", title: "建立資料模型", detail: "把欄位、實體、關係、版本與來源整理成可維護結構。" },
  { step: "03", title: "做出可用介面", detail: "依需求規劃查詢頁、Dashboard、後台、API 或視覺化介面。" },
  { step: "04", title: "加上可信脈絡", detail: "針對 DPP、ESG 或稽核資料設計來源、版本與查核節點。" },
];
